# Generated by Django 3.0.8 on 2020-07-12 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_check_historicalcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='end_check',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event End Time'),
        ),
        migrations.AlterField(
            model_name='historicalcheck',
            name='end_check',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event End Time'),
        ),
    ]
