# Generated by Django 3.0.8 on 2020-07-12 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200712_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCheck',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('start_check', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Start Time')),
                ('end_check', models.DateField(default=django.utils.timezone.now, verbose_name='Event End Time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.mainsite.Course', verbose_name='Course of Check')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical check',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_check', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Start Time')),
                ('end_check', models.DateField(default=django.utils.timezone.now, verbose_name='Event End Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.mainsite.Course', verbose_name='Course of Check')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
